### ISSUE TITLE
npm start => path.exists undefined

### ISSUE THREAD

**Issue by miaoski** [audreyt/moedict-webkit#170]
```
$ npm start
===> http://127.0.0.1:8888/
/Users/.../github/moedict-webkit/static-here.js:77
  path.exists(filename, function (exists) {
       ^
TypeError: undefined is not a function
    at Server.httpCb (/Users/.../github/moedict-webkit/static-here.js:77:8)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```
環境
node.js v0.12.4
LiveScript version 1.3.1
npm 2.10.1
gulp
[17:30:00] CLI version 3.9.0
[17:30:00] Local version 3.8.11

**Comment by audreyt** [comment]
See the `master` branch https://github.com/audreyt/moedict-webkit/blob/master/static-here.js#L77 which contains a workaround
